In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import os
import warnings
from PIL import Image 
import matplotlib.pyplot as plt
import time
from tkinter import *
import tkinter.messagebox
warnings.filterwarnings('ignore')

pygame 2.1.2 (SDL 2.0.18, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\Admin\source\Driver-Drowsiness-Detection-using-Deep-Learning-main\model\model.h5')

In [3]:
root=Tk()
root.geometry('700x300')
frame = Frame(root, relief=RIDGE, borderwidth=2)
frame.pack(fill=BOTH,expand=1)
root.title('Drowsiness Detection Cam')
frame.config(background='light blue')
label = Label(frame, text="Drowsiness Detection Cam",bg='light blue',font=('Times 35 bold'))
label.pack(side=TOP)
filename = PhotoImage(file="C:/Users/Admin/source/Driver-Drowsiness-Detection-using-Deep-Learning-main/demo.png", master=root)
background_label = Label(frame,image=filename)
background_label.pack(side=TOP)

In [4]:
def anotherWin():
   tkinter.messagebox.showinfo("About",'Drowsiness Detection Cam \n Made Using\n-Transfer Learning\n-OpenCV\n-Numpy\n-Tkinter\n In Python 3.8.8')

In [5]:
menu = Menu(root)
root.config(menu=menu)

subm2 = Menu(menu)
menu.add_cascade(label="About",menu=subm2)
subm2.add_command(label="Drowsiness Detection Cam",command=anotherWin)

In [6]:
def web():
   capture =cv2.VideoCapture(0)
   while True:
      ret,frame=capture.read()
      gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
      cv2.imshow('frame',frame)
      if cv2.waitKey(1) & 0xFF ==ord('q'):
         break
   capture.release()
   cv2.destroyAllWindows()

In [7]:
def alert():
   mixer.init()
   alert=mixer.Sound('alarm_out.wav')
   alert.play()
   time.sleep(0.001)
   alert.play()  

In [8]:
def blink():
    
    cap = cv2.VideoCapture(0)
    Score = 0
    while True:
        ret, frame = cap.read()
        height,width = frame.shape[0:2]
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.3, minNeighbors=5)
        eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
        cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
        for (x,y,w,h) in faces:
            cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
            # preprocessing steps
            eye= frame[ey:ey+eh,ex:ex+ew]
            eye= cv2.resize(eye,(224,224))
            eye= eye/255
            eye= eye.reshape(224,224,3)
            eye= np.expand_dims(eye,axis=0)
            # preprocessing is done now model prediction
            prediction = model.predict(eye)
            print(prediction)
        
            # if eyes are closed
            if prediction[0][0]>0.30:
                cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                           thickness=1,lineType=cv2.LINE_AA)
                cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=0.8,color=(255,255,255),
                           thickness=1,lineType=cv2.LINE_AA)
                #sound.play()
                Score=Score+1
                if(Score>10):
                    try:
                        alert()
                        Score=0
                    except:
                        pass
            
            # if eyes are open
            elif prediction[0][1]>0.60:
                cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                           thickness=1,lineType=cv2.LINE_AA)      
                cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=0.8,color=(255,255,255),
                           thickness=1,lineType=cv2.LINE_AA)
                Score = Score-1
                if (Score<9):
                    Score=0
            
        
        cv2.imshow('frame',frame)
        if cv2.waitKey(33) & 0xFF==ord('q'):
            break
        
    cap.release()
    cv2.destroyAllWindows()

but1=Button(frame,padx=5,pady=5,width=39,bg='white',fg='black',relief=GROOVE,command=web,text='Open Cam',font=('helvetica 15 bold'))
but1.place(x=450,y=304)

but2=Button(frame,padx=5,pady=5,width=39,bg='white',fg='black',relief=GROOVE,command=blink,text='Detect Drowsiness With Alarm',font=('helvetica 15 bold'))
but2.place(x=450,y=376)


root.mainloop()

[[0.9274406 0.0725594]]
[[0.9818341  0.01816591]]
[[0.97949904 0.020501  ]]
[[0.86941755 0.13058244]]
[[0.9753432  0.02465676]]
[[0.85876536 0.1412347 ]]
[[1.3842333e-04 9.9986160e-01]]
[[0.9936395  0.00636043]]
[[0.9261624  0.07383753]]
[[0.9969343  0.00306572]]
[[0.97278816 0.02721187]]
[[0.68559146 0.31440854]]
[[0.9847557 0.0152443]]
[[0.9686119  0.03138808]]
[[0.9004328  0.09956712]]
[[0.9885875  0.01141251]]
[[0.8827471  0.11725292]]
[[6.353603e-06 9.999937e-01]]
[[0.6479018 0.3520982]]
[[0.9891311  0.01086894]]
[[0.97454107 0.0254589 ]]
[[0.43875372 0.5612463 ]]
[[0.85452265 0.14547728]]
[[9.9996424e-01 3.5786004e-05]]
[[9.9983478e-01 1.6517565e-04]]
[[0.9624491  0.03755097]]
[[0.78939354 0.21060644]]
[[9.9949443e-01 5.0555752e-04]]
[[0.9917108  0.00828914]]
[[0.99834025 0.00165972]]
[[0.01006259 0.9899374 ]]
[[0.96986145 0.03013862]]
[[0.9877365  0.01226355]]
[[6.5686786e-06 9.9999344e-01]]
[[9.9997592e-01 2.4047004e-05]]
[[0.9982034  0.00179653]]
[[0.98449373 0.01550625]]
[[0.

[[0.04836319 0.9516368 ]]
[[0.9590808  0.04091916]]
[[0.8996199  0.10038009]]
[[0.9748377  0.02516227]]
[[0.22942491 0.77057505]]
[[0.82660466 0.17339534]]
[[0.8464275  0.15357247]]
[[0.96287066 0.03712939]]
[[0.9749765  0.02502356]]
[[0.9986265  0.00137352]]
[[0.9965402  0.00345987]]
[[9.9972719e-01 2.7280225e-04]]
[[0.00863802 0.99136204]]
[[0.00189577 0.9981042 ]]
[[0.78690314 0.21309686]]
[[0.2940051 0.7059949]]
[[9.992513e-01 7.486376e-04]]
[[0.21531594 0.784684  ]]
[[0.9425599  0.05744007]]
[[0.31497657 0.68502337]]
[[2.1538941e-05 9.9997842e-01]]
[[0.26175493 0.73824507]]
[[0.5403128 0.4596872]]
[[0.83953834 0.16046174]]
[[0.821182   0.17881806]]
[[0.7776041  0.22239587]]
[[0.4577379 0.5422621]]
[[0.7697746  0.23022541]]
[[0.8871206  0.11287943]]
[[0.8652208  0.13477926]]
[[0.8189408  0.18105921]]
[[0.969647   0.03035305]]
[[0.8149686 0.1850314]]
[[0.98283017 0.01716982]]
[[0.9490215  0.05097845]]
[[0.97529614 0.02470387]]
[[0.98848546 0.01151451]]
[[0.89322686 0.10677315]]
[[0.

[[0.9764653  0.02353469]]
[[0.9963117  0.00368829]]
[[0.9942193  0.00578074]]
[[0.9952799  0.00472017]]
[[9.9973005e-01 2.6995232e-04]]
[[0.53493524 0.46506482]]
[[0.9937104  0.00628966]]
[[0.99543446 0.00456553]]
[[0.99807656 0.00192347]]
[[0.9252395  0.07476055]]
[[0.99552745 0.00447254]]
[[9.9998367e-01 1.6340044e-05]]
[[0.9860307  0.01396923]]
[[0.80591756 0.19408244]]
[[0.9483271  0.05167284]]
[[0.9427843  0.05721568]]
[[0.99615663 0.00384339]]
[[9.9960428e-01 3.9575703e-04]]
[[9.9978250e-01 2.1745772e-04]]
[[0.01181172 0.9881883 ]]
[[9.9995852e-01 4.1460306e-05]]
[[0.9984756  0.00152443]]
[[0.9985196  0.00148037]]
[[5.310481e-04 9.994690e-01]]
[[9.9959844e-01 4.0157771e-04]]
[[0.89447916 0.10552087]]
[[9.999300e-01 6.992962e-05]]
[[9.992792e-01 7.207624e-04]]
[[0.9156158  0.08438423]]
[[0.9888974  0.01110258]]
[[3.8115583e-10 1.0000000e+00]]
[[9.99896288e-01 1.03646635e-04]]
[[0.8687498  0.13125019]]
[[9.9991035e-01 8.9680107e-05]]
[[9.9979550e-01 2.0448957e-04]]
[[0.9734195 0.02

[[0.9683034  0.03169659]]
[[9.9974436e-01 2.5565131e-04]]
[[0.10888747 0.8911125 ]]
[[1.5717350e-06 9.9999845e-01]]
[[0.22999564 0.7700044 ]]
[[0.9760936  0.02390642]]
[[0.9482149  0.05178512]]
[[0.9588875  0.04111249]]
[[0.99128526 0.00871473]]
[[0.9981249  0.00187505]]
[[0.9929103  0.00708961]]
[[9.9996424e-01 3.5718869e-05]]
[[0.9507981  0.04920195]]
[[0.9957759 0.0042241]]
[[0.9853904  0.01460957]]
[[9.9937785e-01 6.2210951e-04]]
[[0.9982267  0.00177331]]
[[0.7529558  0.24704425]]
[[9.9957269e-01 4.2725675e-04]]
[[0.9979919  0.00200808]]
[[0.8467476  0.15325242]]
[[0.9811427  0.01885736]]
[[9.9959308e-01 4.0691879e-04]]
[[0.00382658 0.99617344]]
[[0.7422134  0.25778663]]
[[0.82970124 0.17029876]]
[[1.0783134e-04 9.9989212e-01]]
[[0.96143764 0.03856239]]
[[1.0366977e-04 9.9989629e-01]]
[[0.07706632 0.9229337 ]]
[[0.1802915  0.81970847]]
[[0.50905895 0.49094114]]
[[9.9967206e-01 3.2791737e-04]]
[[3.4446359e-07 9.9999964e-01]]
[[0.15534157 0.84465843]]
[[9.9986541e-01 1.3461742e-04]]


[[0.9832897 0.0167103]]
[[0.33781767 0.66218233]]
[[0.9473798  0.05262019]]
[[0.9129325  0.08706757]]
[[9.9991715e-01 8.2882121e-05]]
[[0.9954112  0.00458884]]
[[0.984054   0.01594597]]
[[0.9835048 0.0164953]]
[[0.9969195  0.00308056]]
[[9.9954128e-01 4.5878065e-04]]
[[0.99701726 0.00298269]]
[[0.9964444  0.00355558]]
[[0.9985495  0.00145051]]
[[0.995631   0.00436901]]
[[0.970957   0.02904301]]
[[0.96640277 0.03359725]]
[[0.9851667  0.01483327]]
[[9.9954021e-01 4.5987437e-04]]
[[0.9490376 0.0509624]]
[[0.447723 0.552277]]
[[0.96820754 0.0317925 ]]
[[0.9800386  0.01996144]]
[[9.9976844e-01 2.3160318e-04]]
[[9.996184e-01 3.815286e-04]]
[[0.9798765  0.02012346]]
[[9.3346095e-04 9.9906653e-01]]
[[0.8729287  0.12707137]]
[[0.9025381  0.09746184]]
[[0.99715155 0.00284847]]
[[0.87511253 0.12488747]]
[[9.995765e-01 4.234776e-04]]
[[0.99131155 0.00868852]]
[[0.9898343  0.01016567]]
[[9.996487e-01 3.512875e-04]]
[[0.998478   0.00152207]]
[[0.9747458  0.02525414]]
[[0.9772231 0.0227769]]
[[0.3850

[[0.9988701  0.00112985]]
[[0.76155305 0.23844697]]
[[9.9953973e-01 4.6034498e-04]]
[[9.999931e-01 6.937085e-06]]
[[0.98199147 0.01800849]]
[[0.9201736  0.07982641]]
[[0.88988966 0.1101103 ]]
[[0.96595556 0.03404443]]
[[0.98986036 0.01013963]]
[[0.99822825 0.00177176]]
[[0.99876535 0.00123462]]
[[0.9917795  0.00822049]]
[[9.9997699e-01 2.2953867e-05]]
[[0.8460465  0.15395343]]
[[0.9985238  0.00147631]]
[[0.91526294 0.08473711]]
[[0.02479691 0.97520304]]
[[9.9929762e-01 7.0231257e-04]]
[[0.9979259  0.00207415]]
[[0.84594643 0.15405358]]
[[0.00109334 0.9989066 ]]
[[0.8638692  0.13613081]]
[[0.9838472  0.01615274]]
[[0.99798834 0.0020116 ]]
[[0.9977533  0.00224665]]
[[0.9983205  0.00167945]]
[[9.993036e-01 6.964208e-04]]
[[9.9952555e-01 4.7445094e-04]]
[[0.96600795 0.0339921 ]]
[[0.98952687 0.01047319]]
[[0.77054334 0.22945662]]
[[0.99051464 0.00948537]]
[[0.9715328  0.02846714]]
[[0.9905449  0.00945505]]
[[0.9037771  0.09622286]]
[[0.99676836 0.00323164]]
[[0.24864678 0.75135326]]
[[0.99

[[0.9927463  0.00725364]]
[[9.9999785e-01 2.1740002e-06]]
[[0.0199491  0.98005086]]
[[9.992198e-01 7.802638e-04]]
[[0.9896688  0.01033123]]
[[0.9880927 0.0119073]]
[[9.999331e-01 6.684026e-05]]
[[9.998185e-01 1.815491e-04]]
[[0.9891795  0.01082055]]
[[0.00166731 0.9983327 ]]
[[0.87074584 0.1292541 ]]
[[0.9920953  0.00790467]]
[[0.97778803 0.02221191]]
[[0.98632044 0.01367954]]
[[0.94774556 0.05225437]]
[[0.9960238  0.00397624]]
[[0.6636855  0.33631444]]
[[0.8643453  0.13565466]]
[[0.00371112 0.9962889 ]]
[[9.9986756e-01 1.3239928e-04]]
[[0.72374785 0.27625215]]
[[0.9974694  0.00253055]]
[[9.9959725e-01 4.0271934e-04]]
[[9.9938321e-01 6.1670726e-04]]
[[0.99399096 0.00600902]]
[[0.99850047 0.0014995 ]]
[[0.8044914  0.19550857]]
[[0.99850154 0.00149847]]
[[0.51175094 0.4882491 ]]
[[9.9934465e-01 6.5528770e-04]]
[[0.98826665 0.01173339]]
[[9.9980968e-01 1.9031206e-04]]
[[0.9359009  0.06409907]]
[[0.80116516 0.19883479]]
[[9.9961424e-01 3.8571376e-04]]
[[0.970416   0.02958392]]
[[0.83863896

[[0.96067387 0.03932614]]
[[0.00531634 0.9946837 ]]
[[9.999310e-01 6.905088e-05]]
[[0.98630816 0.0136919 ]]
[[9.9992979e-01 7.0240676e-05]]
[[5.947256e-12 1.000000e+00]]
[[9.999608e-01 3.926047e-05]]
[[9.9999034e-01 9.6241283e-06]]
[[0.98553944 0.01446057]]
[[0.00179995 0.99820006]]
[[9.9940073e-01 5.9928250e-04]]
[[9.9998593e-01 1.4102443e-05]]
[[0.9647289  0.03527112]]
[[0.84365594 0.15634398]]
[[5.3159192e-11 1.0000000e+00]]
[[9.999286e-01 7.141561e-05]]
[[0.00259301 0.997407  ]]
[[9.9988508e-01 1.1487529e-04]]
[[9.9999702e-01 2.9565447e-06]]
[[0.9989692  0.00103084]]
[[9.9981838e-01 1.8165592e-04]]
[[0.25416386 0.7458361 ]]
[[9.9999177e-01 8.1969865e-06]]
[[9.9998021e-01 1.9833764e-05]]
[[0.9977865  0.00221343]]
[[9.9994433e-01 5.5667166e-05]]
[[1.5978524e-11 1.0000000e+00]]
[[0.26604208 0.73395795]]
[[0.99711573 0.00288429]]
[[9.999906e-01 9.362947e-06]]
[[5.1129387e-06 9.9999487e-01]]
[[9.9997473e-01 2.5254833e-05]]
[[0.5764307  0.42356932]]
[[0.00322816 0.9967719 ]]
[[0.6838386 

[[0.9773286  0.02267138]]
[[0.98103863 0.01896139]]
[[0.9857329  0.01426704]]
[[0.90510696 0.09489307]]
[[0.33072615 0.66927385]]
[[0.87836564 0.12163439]]
[[0.9989675  0.00103247]]
[[0.99829406 0.0017059 ]]
[[0.76902336 0.23097667]]
[[0.5885677  0.41143227]]
[[0.00615498 0.9938451 ]]
[[9.9961084e-01 3.8923358e-04]]
[[0.9769718  0.02302825]]
[[0.01738251 0.98261756]]
[[0.2547783 0.7452217]]
[[0.0575001 0.9424999]]
[[0.1340133 0.8659867]]
[[0.9988192  0.00118075]]
[[0.853499   0.14650102]]
[[0.3907587 0.6092413]]
[[9.994487e-01 5.512454e-04]]
[[0.9908845  0.00911548]]
[[0.98254824 0.01745174]]
[[0.7865367  0.21346329]]
[[0.01601183 0.9839881 ]]
[[0.799605   0.20039506]]
[[0.18606791 0.8139321 ]]
[[0.9986576  0.00134236]]
[[0.9968857  0.00311423]]
[[1.5299063e-05 9.9998474e-01]]
[[0.90516347 0.09483657]]
[[0.19623709 0.8037629 ]]
[[9.9966621e-01 3.3375187e-04]]
[[0.98670644 0.01329354]]
[[0.86198175 0.13801825]]
[[9.999163e-01 8.363094e-05]]
[[9.8216867e-07 9.9999905e-01]]
[[0.43763292 0

[[0.99435186 0.00564816]]
[[0.08369183 0.91630816]]
[[0.42351857 0.57648146]]
[[0.99851674 0.0014833 ]]
[[9.9939895e-01 6.0104660e-04]]
[[0.98531216 0.01468779]]
[[9.9956411e-01 4.3587355e-04]]
[[9.999124e-01 8.758898e-05]]
[[0.4900202  0.50997984]]
[[9.993799e-01 6.200750e-04]]
[[0.9548769  0.04512307]]
[[0.972575   0.02742503]]
[[0.8053554  0.19464451]]
[[0.9938492  0.00615086]]
[[0.9252627  0.07473733]]
[[0.00407788 0.9959221 ]]
[[9.998023e-01 1.977399e-04]]
[[9.9999607e-01 3.9271645e-06]]
[[0.99394715 0.00605286]]
[[9.9927455e-01 7.2550925e-04]]
[[0.5985441  0.40145585]]
[[0.02541077 0.9745892 ]]
[[0.770458   0.22954196]]
[[9.9999440e-01 5.6252925e-06]]
[[0.9908715 0.0091285]]
[[0.8275066  0.17249343]]
[[0.05749183 0.94250816]]
[[0.666735   0.33326498]]
[[0.9972799  0.00272012]]
[[0.95522934 0.04477067]]
[[0.00867594 0.99132407]]
[[0.97147715 0.02852284]]
[[0.8272832  0.17271678]]
[[0.90238404 0.09761597]]
[[0.9855327  0.01446728]]
[[0.998979   0.00102103]]
[[0.45147383 0.5485261 ]

[[0.45862523 0.54137474]]
[[0.93628615 0.06371386]]
[[0.80201006 0.19798996]]
[[0.7837364  0.21626359]]
[[0.28658554 0.71341443]]
[[9.551952e-05 9.999045e-01]]
[[9.993698e-01 6.301843e-04]]
[[0.9954464 0.0045536]]
[[0.82543474 0.17456523]]
[[0.99471986 0.00528018]]
[[0.98614776 0.01385221]]
[[0.98613656 0.01386344]]
[[0.98522645 0.01477352]]
[[0.47413182 0.5258682 ]]
[[0.43676278 0.5632372 ]]
[[9.0898839e-06 9.9999094e-01]]
[[0.9802786  0.01972134]]
[[0.98483247 0.01516758]]
[[0.8191373  0.18086274]]
[[0.01274294 0.98725706]]
[[9.9965715e-01 3.4289964e-04]]
[[0.62493616 0.3750638 ]]
[[0.9465913  0.05340873]]
[[0.68371403 0.3162859 ]]
[[0.9791291  0.02087088]]
[[0.84678024 0.15321974]]
[[0.9947636  0.00523638]]
[[0.98474276 0.01525722]]
[[0.9710352 0.0289648]]
[[0.96557105 0.034429  ]]
[[0.94476104 0.05523894]]
[[0.07414151 0.92585856]]
[[0.97611326 0.02388675]]
[[4.8608194e-06 9.9999511e-01]]
[[0.979001   0.02099899]]
[[0.9717026  0.02829746]]
[[9.9937016e-01 6.2989490e-04]]
[[0.941746

[[0.9984804  0.00151968]]
[[0.9824454  0.01755457]]
[[0.9852502  0.01474983]]
[[0.9989691  0.00103093]]
[[0.04955344 0.95044655]]
[[0.93729484 0.06270519]]
[[0.12324851 0.8767515 ]]
[[0.99603504 0.00396497]]
[[0.08385067 0.9161494 ]]
[[9.999646e-01 3.538769e-05]]
[[0.00826869 0.99173135]]
[[0.9989311  0.00106889]]
[[0.9918105  0.00818952]]
[[1.4881945e-05 9.9998510e-01]]
[[0.78564477 0.21435525]]
[[9.999907e-01 9.251192e-06]]
[[0.9976726  0.00232734]]
[[3.072365e-04 9.996928e-01]]
[[0.52285033 0.4771497 ]]
[[0.43317574 0.5668242 ]]
[[0.04358877 0.9564112 ]]
[[9.9954188e-01 4.5811982e-04]]
[[9.9999714e-01 2.9176615e-06]]
[[0.9788046  0.02119539]]
[[0.00760526 0.9923948 ]]
[[0.00611718 0.9938829 ]]
[[0.98901355 0.01098653]]
[[0.9842275 0.0157725]]
[[9.9994183e-01 5.8156675e-05]]
[[0.00790505 0.99209493]]
[[1.5628756e-04 9.9984372e-01]]
[[0.02775246 0.97224754]]
[[0.80512697 0.19487306]]
[[0.9750299  0.02497019]]
[[0.99807453 0.00192545]]
[[0.00547716 0.9945228 ]]
[[0.83880234 0.1611977 ]

[[0.9211336  0.07886642]]
[[9.9960202e-01 3.9796566e-04]]
[[0.27323565 0.7267644 ]]
[[0.9888678 0.0111322]]
[[0.95546955 0.04453041]]
[[0.9920941  0.00790595]]
[[0.99750227 0.00249779]]
[[7.654369e-11 1.000000e+00]]
[[0.99831164 0.00168841]]
[[9.9990976e-01 9.0214642e-05]]
[[0.991682   0.00831798]]
[[1.7848002e-06 9.9999821e-01]]
[[9.994320e-01 5.679847e-04]]
[[0.9673465  0.03265355]]
[[0.99132526 0.0086748 ]]
[[0.8139575 0.1860425]]
[[9.9976140e-01 2.3863111e-04]]
[[0.9942889 0.0057111]]
[[4.3091194e-11 1.0000000e+00]]
[[0.9844573  0.01554264]]
[[0.9744256  0.02557439]]
[[9.9985504e-01 1.4499269e-04]]
[[0.9974274  0.00257263]]
[[0.8266443  0.17335571]]
[[0.9705857  0.02941427]]
[[0.99509877 0.00490121]]
[[0.87963736 0.12036267]]
[[0.00181372 0.9981863 ]]
[[0.9329594  0.06704066]]
[[0.00598158 0.99401844]]
[[0.784704   0.21529596]]
[[9.9915445e-01 8.4560877e-04]]
[[0.9025479  0.09745212]]
[[0.00680149 0.99319845]]
[[0.09633555 0.90366447]]
[[0.27427012 0.7257299 ]]
[[0.31772473 0.68227

[[0.01139088 0.9886091 ]]
[[9.997085e-01 2.914417e-04]]
[[6.6706409e-05 9.9993324e-01]]
[[2.8484089e-07 9.9999976e-01]]
[[9.9998569e-01 1.4259629e-05]]
[[0.9705019  0.02949813]]
[[9.992939e-01 7.060842e-04]]
[[9.9955446e-01 4.4549306e-04]]
[[9.998485e-01 1.514726e-04]]
[[0.9965186  0.00348143]]
[[0.00394717 0.99605286]]
[[9.9980062e-01 1.9938893e-04]]
[[0.99854326 0.00145671]]
[[0.98894066 0.01105929]]
[[0.9985312  0.00146877]]
[[0.89368117 0.10631888]]
[[9.993998e-01 6.002400e-04]]
[[9.9988687e-01 1.1309581e-04]]
[[0.9364654  0.06353454]]
[[0.9401589  0.05984109]]
[[0.57164466 0.42835525]]
[[0.3837288 0.6162712]]
[[0.98117214 0.01882784]]
[[0.9733787  0.02662129]]
[[9.6018562e-07 9.9999905e-01]]
[[9.9946183e-01 5.3818716e-04]]
[[0.703372 0.296628]]
[[0.9974611  0.00253887]]
[[2.8297464e-09 1.0000000e+00]]
[[9.9995744e-01 4.2554191e-05]]
[[9.999094e-01 9.057927e-05]]
[[0.9614879  0.03851207]]
[[0.20597292 0.7940271 ]]
[[0.9969704  0.00302955]]
[[1.7085233e-07 9.9999988e-01]]
